<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 6/24/2018
 * Time: 4:17 PM
 */

namespace App\Repositories\CandiateInfo;
use App\Model\CandidateInfo;
use App\Repositories\EloquentRepository;

class CandidateInfoEloquentRepository extends EloquentRepository
{
    public function setModel()
    {
        return CandidateInfo::class; // TODO: Change the autogenerated stub
    }

    public function getAll(array $condition = [],$paginate=false, $limit = 10)
    {
        parent::getAll($condition, $limit); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes)
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function updateAjax(array $attributes)
    {
        parent::updateAjax($attributes); // TODO: Change the autogenerated stub
    }
}