version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www/
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    ports:
    - 80:80
  # The Database
  database:
    image: mysql:5.6
    volumes:
    - db:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=homestead" # using when login phpmyadmin
    - "MYSQL_PASSWORD=secret" # using when login phpmyadmin
    - "MYSQL_ROOT_PASSWORD=secret"
    ports:
    - "3306:3306"

  # The Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: homestead # using when login phpmyadmin
      MYSQL_PASSWORD: secret # using when login phpmyadmin
      MYSQL_ROOT_PASSWORD: secret
    ports:
    - "8080:80"
    links:
    # for mysql container - using when login phpmyadmin
    - database

  # The elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  # The npm
  npm:
    image: node
    volumes:
    - ./:/data
    working_dir: /data
    entrypoint: ['npm', '--no-bin-link']
volumes:
  db:
  esdata:
    driver: local
