<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CandidateRequest2 extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'can_name'     => 'required|max:255',
            'can_phone'    => 'required|max:20',
            'can_email'    => 'required|max:255|email',
            'can_address'  => 'max:255',
            'can_skype'    => 'max:255|url|nullable',
            'can_facebook' => 'max:255|url|nullable',
            'can_linkedin' => 'max:255|url|nullable',
            'can_github'   => 'max:255|url|nullable',
        ];
    }

    public function messages()
    {
        return [
            'can_name.required'        => 'Tên không được để trống',
            'can_name.max'             => 'Tên quá dài',
            'can_birthday.required'    => 'Ngày sinh không được để trống',
            'can_birthday.date_format' => 'Bạn phải nhập vào ngày tháng vd: năm-tháng-ngày',
            'can_gender.required'      => 'Bạn phải chọn một giới tính',
            'can_phone.required'       => 'Số điện thoại không được để trống',
            'can_phone.max'            => 'Số điện thoại quá dài',
            'can_email.required'       => 'Email không được để trống',
            'can_email.max'            => 'Email quá dài',
            'can_email.unique'         => 'Email đã tồn tại',
            'can_email.email'          => 'Bạn phải nhập vào một email vd: example@gmail.com',
            'can_location_id.required' => 'Bạn phải chọn quê quán',
            'can_address.required'     => 'Địa chỉ không được để trống',
            'can_address.max'          => 'Địa chỉ quá dài',
            'can_skype.url'            => 'Bạn phải nhập URL skype',
            'can_skype.max'            => 'Địa chỉ Skype quá dài',
            'can_facebook.url'         => 'Bạn phải nhập URL facebook',
            'can_facebook.max'         => 'Địa chỉ Facebook quá dài',
            'can_linkedin.url'         => 'Bạn phải nhập URL linkedin',
            'can_linkedin.max'         => 'Địa chỉ Linkedin quá dài',
            'can_github.url'           => 'Bạn phải nhập URL github',
            'can_github.max'           => 'Địa chỉ Github quá dài',
            'can_source_id.required'   => 'Bạn phải chọn một nguồn',
            'hometown.required'        => 'Bạn phải nhập quê quán'
        ]; // TODO: Change the autogenerated stub
    }
}
