<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 6/24/2018
 * Time: 1:47 PM
 */

namespace App\Repositories\Candidate;

use App\Repositories\EloquentRepository;

use App\Model\Candidate;

class CandidateEloquentRepository extends EloquentRepository
{
    public function setModel()
    {
        return Candidate::class;
        // TODO: Implement setModel() method.
    }

    public function getAll(array $condition = [],$paginate=false, $limit = 10)
    {
        $selectList=$this->_model;

        if ($with=array_get($condition,'with')){
            $selectList=$selectList->with($with);
        }

        if ($select=array_get($condition, 'select')){
            $selectList=$selectList->select($select);
        }

        if ($where=array_get($condition, 'where')){
            $selectList=$selectList->where($where);
        }

        if ($orderby=array_get($condition, 'orderby')){
            $selectList=$selectList->orderBy($orderby['field'],$orderby['type']);
        }

        if ($paginate==true){
            $selectList=$selectList->paginate($limit);
        }elseif(array_get($condition, 'count')==true){
            $selectList = $selectList->count();
        }else{
            $selectList = $selectList->get();
        }

        return $selectList;
        // TODO: Implement getAll() method.
    }

    public function create(array $attributes)
    {

        $candidate=parent::create($attributes); // TODO: Change the autogenerated stub

        return $candidate->id;
    }

    public function updateAjax(array $attributes)
    {
        // TODO: Implement updateAjax() method.
    }
}