<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 6/24/2018
 * Time: 4:55 PM
 */

namespace App\Repositories\CandidateCareer;

use App\Model\CandidateCareer;
use App\Repositories\EloquentRepository;

class CandidateCareerEloquentRepository extends EloquentRepository
{
    public function setModel()
    {
        return CandidateCareer::class;
        // TODO: Implement setModel() method.
    }

    public function getAll(array $condition = [],$paginate=false, $limit = 10)
    {
        // TODO: Implement getAll() method.
    }

    public function create(array $attributes)
    {
        $candidate_career=parent::create($attributes); // TODO: Change the autogenerated stub
        return $candidate_career->id;
    }

    public function updateAjax(array $attributes)
    {
        // TODO: Implement updateAjax() method.
    }
}