<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 6/20/2018
 * Time: 10:15 PM
 */

namespace App\Repositories\Source;

use App\Model\Source;
use App\Repositories\EloquentRepository;

class SourceEloquentRepository extends EloquentRepository
{
    public function setModel()
    {
        return Source::class;
    }

    public function getAll(array $condition = [], $paginate=false, $limit = 10)
    {
        $selectList=$this->_model;

        if ($select=array_get($condition , 'select')){
            $selectList=$selectList->select($select);
        }

        if ($searchName=array_get($condition,'search')){
            $selectList=$selectList->where($searchName['field'],'LIKE','%'.$searchName['string'].'%');
        }

        if ($orderById=array_get($condition,'orderById')){
            $selectList=$selectList->orderBy('id',$orderById);
        }

        if ($where=array_get($condition, 'where')){
            $selectList=$selectList->where($where);
        }

        if ($option=array_get($condition,'searchOption')){
            switch ($option){
                case 'new':
                    $selectList=$selectList->where('id',5);
                    break;
                case 'top':

                    break;

            }
        }

        if ($paginate==true){
            $result=$selectList->paginate($limit);
        }else{
            $result=$selectList->get();
        }

        return $result;

    }

    public function search($string){
        return $this->_model->select('id','so_name')->where('so_name','like','%'.$string.'%')->get();
    }

    public function create(array $attributes)
    {
        $arr=[
            'so_name'=>$attributes['so_name'],
            'so_slug'=>$this->to_slug($attributes['so_name'])
        ];

        return parent::create($arr); // TODO: Change the autogenerated stub
    }

    public function update($id, array $attributes)
    {
        $arr=[
            'so_name'=>strip_tags($attributes['so_name']),
            'so_slug'=>str_slug(strip_tags($attributes['so_name']))
        ];

        return parent::update($id, $arr); // TODO: Change the autogenerated stub
    }

    public function updateAjax(array $attributes)
    {
        $id=$attributes['id'];
        $arr=[
            'so_name'=>strip_tags($attributes['so_name']),
            'so_slug'=>strip_tags($attributes['so_name'])
        ];

        return parent::update($id,$arr); // TODO: Change the autogenerated stub
    }




}