<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 6/20/2018
 * Time: 10:15 PM
 */

namespace App\Repositories\Source;

use App\Model\Source;
use App\Repositories\EloquentRepository;

class SourceEloquentRepository extends EloquentRepository
{
    public function setModel()
    {
        return Source::class;
    }

    public function create(array $attributes)
    {
        $arr=[
            'so_name'=>$attributes['so_name'],
            'so_slug'=>$this->to_slug($attributes['so_name'])
        ];

        parent::create($arr); // TODO: Change the autogenerated stub
    }

    public function update($id, array $attributes)
    {
        $arr=[
            'so_name'=>$attributes['so_name'],
            'so_slug'=>$this->to_slug($attributes['so_name'])
        ];

        return parent::update($id, $arr); // TODO: Change the autogenerated stub
    }


}