<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 6/21/2018
 * Time: 7:41 AM
 */

namespace App\Repositories\Skill;

use App\Model\Skill;
use App\Repositories\EloquentRepository;

class SkillEloquentRepository extends EloquentRepository
{
    public function setModel()
    {
        return Skill::class;
    }

    public function create(array $attributes)
    {
        $arr=[
            'sk_name'=>$attributes['sk_name'],
            'sk_slug'=>$this->to_slug($attributes['sk_name'])
        ];

        parent::create($arr); // TODO: Change the autogenerated stub
    }

    public function update($id, array $attributes)
    {
        $arr=[
            'sk_name'=>$attributes['sk_name'],
            'sk_slug'=>$this->to_slug($attributes['sk_name'])
        ];


        return parent::update($id, $arr); // TODO: Change the autogenerated stub
    }

}