<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 6/21/2018
 * Time: 7:41 AM
 */

namespace App\Repositories\Skill;

use App\Model\Skill;
use App\Repositories\EloquentRepository;

class SkillEloquentRepository extends EloquentRepository
{
    public function setModel()
    {
        return Skill::class;
    }

    public function getAll(array $condition = [],$paginate=false, $limit = 10)
    {
        $selectList=$this->_model;

        if ($select=array_get($condition, 'select')){
            $selectList=$selectList->select($select);
        }
        if ($searchName=array_get($condition,'name')){
            $selectList=$selectList->where('sk_name','LIKE','%'.$searchName.'%');
        }

        if ($orderById=array_get($condition,'orderById')){
            $selectList=$selectList->orderBy('id',$orderById);
        }

        if ($option=array_get($condition,'searchOption')){
            switch ($option){
                case 'new':
                    $selectList=$selectList->where('id',3);
                    break;
                case 'top':

                    break;

            }
        }

        if ($paginate==true){
            $result = $selectList->paginate($limit);
        }else{
            $result = $selectList->get();
        }

        return $result;
    }

    public function search($string){
        if (!empty($string)){
            return $this->_model->select('id', 'sk_name')->where('sk_name', 'like', '%' . $string . '%')->get();
        }
        return $this->_model->select('id','sk_name')->take(15)->get();
    }

    public function create(array $attributes)
    {
        $arr=[
            'sk_name'=>strip_tags($attributes['sk_name']),
            'sk_slug'=>str_slug(strip_tags($attributes['sk_name']))
        ];

        return parent::create($arr); // TODO: Change the autogenerated stub
    }

    public function update($id, array $attributes)
    {
        $arr=[
            'sk_name'=>$attributes['sk_name'],
            'sk_slug'=>$this->to_slug($attributes['sk_name'])
        ];


        return parent::update($id, $arr); // TODO: Change the autogenerated stub
    }

    public function updateAjax(array $attributes)
    {
        $id=$attributes['id'];

        $arr=[
            'sk_name'=>strip_tags($attributes['sk_name']),
            'sk_slug'=>str_slug(strip_tags($attributes['sk_name']))
        ];


        return parent::update($id, $arr); // TODO: Change the autogenerated stub
    }


}